// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbHU6IUVkiGsiqp_YLKc9BFDYXvX3kHHQ',
    appId: '1:100567141756:web:08f17c35218e560280e8f9',
    messagingSenderId: '100567141756',
    projectId: 'sebew-223',
    authDomain: 'sebew-223.firebaseapp.com',
    storageBucket: 'sebew-223.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP5R7HrN1ltKMAO79ifmT-Z77idmmLIGE',
    appId: '1:100567141756:android:bf88f31a6c20411480e8f9',
    messagingSenderId: '100567141756',
    projectId: 'sebew-223',
    storageBucket: 'sebew-223.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Q8YSzl-5t8sBslvo1EgamDPqYO_gHzE',
    appId: '1:100567141756:ios:a56805d6bf086f3f80e8f9',
    messagingSenderId: '100567141756',
    projectId: 'sebew-223',
    storageBucket: 'sebew-223.appspot.com',
    iosBundleId: 'com.example.challengeFront',
  );
}
